-- [
--   _____ ___  ____   ___
--  |_   _/ _ \|  _ \ / _ \
--    | || | | | | | | | | |
--    | || |_| | |_| | |_| |
--    |_| \___/|____/ \___/
--
--  * Make trouble default for quickfix and loclist
--  * A finished test run shouldn't close the loclist
--  * Cant close test summary window with q
--  * don't know how to save files after renaming
--  * sort search (workspace) symbols results by length/match
--  * in python sometimes comments wont shift indent in visual mode
--  * yank history on fzf (or similar)
--  * inline glob for live grep
--    https://github.com/LazyVim/LazyVim/discussions/5174
--    https://github.com/ibhagwan/fzf-lua/issues/167
--
-- ]

-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
