-- [
--   _____ ___  ____   ___
--  |_   _/ _ \|  _ \ / _ \
--    | || | | | | | | | | |
--    | || |_| | |_| | |_| |
--    |_| \___/|____/ \___/
--
--  * Make trouble default for quickfix and loclist
--  * A finished test run shouldn't close the loclist
--  * Cant close summary window with q
--  * don't know how to save files after renaming
--  * copilot chat history?
--  * look into this coloscheme https://github.com/rebelot/kanagawa.nvim
--  * sort search (workspace) symbols results by length/match
--  * keymap for evaluating arithmetic expressions in insert mode
--  * neovim adds line breaks automatically leading to broken python syntax
--
-- ]

-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
