-- [
--   _____ ___  ____   ___
--  |_   _/ _ \|  _ \ / _ \
--    | || | | | | | | | | |
--    | || |_| | |_| | |_| |
--    |_| \___/|____/ \___/
--
--  * Try codecompanion when 18.0 is out
--    https://github.com/olimorris/codecompanion.nvim/pull/2439
--  * Make neotest notify on test run (success/failure)
--  * Make trouble default for quickfix and loclist
--  * in python sometimes comments wont shift indent in visual mode
--  * yank history on fzf (or similar)
--  * inline glob for live grep
--    https://github.com/LazyVim/LazyVim/discussions/5174
--    https://github.com/ibhagwan/fzf-lua/issues/167
--  * look into neoconf
--    https://github.com/folke/neoconf.nvim
--  * make moving stuff around easier
--    https://github.com/alexpasmantier/pymple.nvim
--
-- ]

-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
